In [1]:
from ola2022_project.environment.environment import get_day_of_interactions, example_environment
import numpy as np

In [2]:
env = example_environment()
a = get_day_of_interactions(np.random.default_rng(), 1000, [70,30,50,40,0], env, deterministic=True)
foo = [[elem.items_bought for elem in a if elem.landed_on == i] for i in range(5)]

In [3]:
e = []
f = []
for items in foo:
    e.append(np.sum(items, axis=0))
    f.append(len(items))
    
e, f

([array([164,  19, 114,  10,  16]),
  array([ 4, 13,  7,  0,  0]),
  array([ 3,  9, 74,  1,  6]),
  array([ 0,  1,  0, 10,  8]),
  0.0],
 [164, 26, 74, 13, 0])

In [4]:
multipliers = []
for rew, n in zip(e,f):
    multipliers.append(np.sum(rew*env.product_prices, axis=0)/n)
multipliers

TypeError: can't multiply sequence by non-int of type 'numpy.float64'

In [5]:
from ola2022_project.algorithms.reward_estimator import compute_reward_multiplier, find_optimal_arms

In [17]:
find_optimal_arms(env, np.linspace(0,400,20), 1000)

array([6, 4, 7, 2, 0])

In [24]:
a = get_day_of_interactions(np.random.default_rng(), 1000, [80,80,80,80,80], env, deterministic=True)

In [25]:
rew = [e.items_bought for e in a]
rew = np.array(rew)
rew

array([[1, 0, 1, 0, 0],
       [1, 0, 1, 0, 0],
       [1, 0, 1, 0, 0],
       ...,
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 1],
       [0, 0, 0, 0, 1]])

In [27]:
np.sum(np.sum(rew, axis=0) * env.product_prices) * np.mean([1,3])

8718.0